### ISSUE TITLE
script issue

### ISSUE THREAD

**Issue by trekkie357** [esi/esi-docs#28]
the script editor is giving an error of "Missing ) after formal parameters. (line 11, file "location")"
on each script i use 

please pardon my noobness i did google the problem but couldn't figure it out

**Comment by jowrjowr** [comment]
this looks like a scripting issue.

come join us on #esi or #devfleet on tweetfleet slack so we aren't doing support via github issue

https://www.fuzzwork.co.uk/tweetfleet-slack-invites/

**Comment by Blacksmoke16** [comment]
@trekkie357 do you happen to be using GESI?

**Comment by trekkie357** [comment]
Yes latest version

**Comment by Blacksmoke16** [comment]
This issue would prob be more suited to https://github.com/Blacksmoke16/GESI in that case.

I'm going to close this since its not really an ESI question.

https://discordapp.com/invite/eEAH2et Is also discord server for GESI specific questions.

**Comment by trekkie357** [comment]
sent email to the mods to join
